# Generated by Django 4.0.1 on 2022-02-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
