# Generated by Django 4.0.1 on 2022-02-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO vehicles_brands (name) VALUES ('Ford'), ('Honda');"),
        migrations.RunSQL("INSERT INTO vehicles_vehicles (name, brand_id) VALUES ('Focus', 1), ('Explorer', 1), ('Civic', 2), ('CRV', 2);")
    ]
