# Generated by Django 4.0.1 on 2022-02-08 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20220202_2157'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO vehicles_brands (name) VALUES ('Tesla'), ('Audi');"),
        migrations.RunSQL("INSERT INTO vehicles_vehicles (name, brand_id) VALUES ('Model S', 3), ('Model 3', 3), ('Q4 e-tron', 4), ('Q3', 4);"),
    ]
